apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  - apiGroups:
      - schedar.task.io
    resources:
      - simplepostgresqls
    verbs:
      - get
      - list
      - patch
      - update
      - watch
      - create
  - apiGroups:
      - stackgres.io
    resources:
      - sgpgconfigs
    verbs:
      - get
      - list
      - patch
      - update
      - watch
      - create